package do_tasks;

public class Arithmetic_exception_trycatch {

}
